export  const LOAD_FLIGHTS_DATA              = 'LOAD FLIGH DATA';
export const LOAD_FLIGHTS_DATA_SUCCESS      = 'LOAD_FLIGHTS_DATA_SUCCESS';
export const LOAD_PASSENGERS_DATA           = 'LOAD PASSENGERS_DATA';
export const LOAD_PASSENGERS_DATA_SUCCESS   = 'LOAD_PASSENGERS_DATA_SUCCESS';
export const CREATE_ANCILLARY = 'CREATE_ANCILLARY';
export const ADD_ANCILLARY = 'ADD_ANCILLARY';
export const UPDATE_ANCILLARY = 'UPDATE_ANCILLARY';
export const UPDATE_ANCILLARY_SUCCESS = 'UPDATE_ANCILLARY_SUCCESS';
export const DELETE_ANCILLARY = 'DELETE_ANCILLARY';
export const DELETE_ANCILLARY_SUCCESS = 'DELETE_ANCILLARY_SUCCESS';

export const CREATE_SPECIAL_MEALS = 'CREATE_SPECIAL_MEALS';
export const ADD_SPECIAL_MEALS = 'ADD_SPECIAL_MEALS';

export const UPDATE_SPECIAL_MEALS = 'UPDATE_SPECIAL_MEALS';
export const UPDATE_SPECIAL_MEALS_SUCCESS = 'UPDATE_SPECIAL_MEALS_SUCCESS';

export const DELETE_SPECIAL_MEALS = 'DELETE_SPECIAL_MEALS';
export const DELETE_SPECIAL_MEALS_SUCCESS = 'DELETE_SPECIAL_MEALS_SUCCESS';

export const CREATE_SHOPPING_ITEMS = 'CREATE_SHOPPING_ITEMS';
export const ADD_SHOPPING_ITEMS = 'ADD_SHOPPING_ITEMS';

export const UPDATE_SHOPPING_ITEMS = 'UPDATE_SHOPPING_ITEMS';
export const UPDATE_SHOPPING_ITEMS_SUCCESS = 'UPDATE_SHOPPING_ITEMS_SUCCESS';

export const DELETE_SHOPPING_ITEMS = 'DELETE_SHOPPING_ITEMS';
export const DELETE_SHOPPING_ITEMS_SUCCESS = 'DELETE_SHOPPING_ITEMS_SUCCESS';