
export const ADD_PASSENGER               = 'ADD PASSENGER';
export const CREATE_PASSENGER            = 'CREATE_PASSENGER';
export const UPDATE_PASSENGER            = 'UPDATE PASSENGER';
export const UPDATE_PASSENGER_SUCCESS    = 'UPDATE PASSENGER_SUCCESS';
export const ADD_ANCILLARY_SERVICES      = 'ADD ANCILLARY SERVICES';
export const UPDATE_ANCILLARY_SERVICES   = 'UPDATE ANCILLARY SERVICES';
export const DELETE_ANCILLARY_SERVICES   = 'DELETE ANCILLARY SERVICES';